version: '3'

services:
  flask-app:
    image: dereknan/cloud_client
    build:
      context: .
    container_name: pythonFlaskApp
    ports:
      - "80:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    depends_on:
      - db
    networks:
      - mynetwork
  db:
    image: postgres:latest
    container_name: postgresdb
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - mynetwork

networks:
  mynetwork: {}

volumes:
  postgres_data: {}
    