# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: federated.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x65\x64\x65rated.proto\x12\tfederated\"\x1d\n\x0cModelRequest\x12\r\n\x05model\x18\x01 \x01(\x0c\"\x1e\n\x0bModel_Reply\x12\x0f\n\x07message\x18\x01 \x01(\t2K\n\tFederated\x12>\n\tSendModel\x12\x17.federated.ModelRequest\x1a\x16.federated.Model_Reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MODELREQUEST']._serialized_start=30
  _globals['_MODELREQUEST']._serialized_end=59
  _globals['_MODEL_REPLY']._serialized_start=61
  _globals['_MODEL_REPLY']._serialized_end=91
  _globals['_FEDERATED']._serialized_start=93
  _globals['_FEDERATED']._serialized_end=168
# @@protoc_insertion_point(module_scope)
