apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdserver
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fdserver
  template:
    metadata:
      labels:
        app: fdserver
    spec:
      containers:
        - name: fdserver
          image: dereknan/cloud-server-arm64:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Singapore
            - name: DATABASE_URL
              value: "postgresql://user:password@postgres-service:5432/mydatabase"
---
apiVersion: v1
kind: Service
metadata:
  name: fdserver
  namespace: default
spec:
  selector:
    app: fdserver
  ports:
    - name: port-0
      port: 50051
      targetPort: 50051
  type: LoadBalancer

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-server
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-server
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh","-c","sleep 20 && PGPASSWORD=$POSTGRES_PASSWORD psql -w -d $POSTGRES_DB -U $POSTGRES_USER -c 
                'CREATE TABLE IF NOT EXISTS globalmodel(id SERIAL PRIMARY KEY, timestamp TEXT NOT NULL, picklefile BYTEA NOT NULL);'"]
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: mydatabase
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password          
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim-server

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432  # The PostgreSQL port
      targetPort: 5432  # The port inside the PostgreSQL container

