# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FD.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x46\x44.proto\"\x18\n\x05\x43hunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"%\n\x12UploadFileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2;\n\x0cModelService\x12+\n\nUploadFile\x12\x06.Chunk\x1a\x13.UploadFileResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FD_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHUNK']._serialized_start=12
  _globals['_CHUNK']._serialized_end=36
  _globals['_UPLOADFILERESPONSE']._serialized_start=38
  _globals['_UPLOADFILERESPONSE']._serialized_end=75
  _globals['_MODELSERVICE']._serialized_start=77
  _globals['_MODELSERVICE']._serialized_end=136
# @@protoc_insertion_point(module_scope)
