version: '3'

services:
  model-training-app:
    image: dereknan/model-test-x86:latest
    container_name: FDModelTest
    environment:
      - MODEL=baseModel.pkl
    volumes:
      - /home/derek/TestingPython:/model
